/**
 * This file was generated by the JPA Modeler
 */
package entity;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

@Entity
public class Persona {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String cognome;

    @Basic
    private String nome;

    /**
     * Lista Prestazioni Ricevute
     */
    @OneToMany(targetEntity = Prestazione.class, mappedBy = "personaID_R")
    private List<Prestazione> prestaziones_R;

    /**
     * Lista Prestazioni Fatte
     */
    @OneToMany(targetEntity = Prestazione.class, mappedBy = "personaID_F")
    private List<Prestazione> prestaziones_F;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCognome() {
        return this.cognome;
    }

    public void setCognome(String cognome) {
        this.cognome = cognome;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public List<Prestazione> getPrestaziones_R() {
        if (prestaziones_R == null) {
            prestaziones_R = new ArrayList<>();
        }
        return this.prestaziones_R;
    }

    public void setPrestaziones_R(List<Prestazione> prestaziones_R) {
        this.prestaziones_R = prestaziones_R;
    }

    public void addPrestaziones_R(Prestazione prestaziones_R) {
        getPrestaziones_R().add(prestaziones_R);
        prestaziones_R.setPersonaID_R(this);
    }

    public void removePrestaziones_R(Prestazione prestaziones_R) {
        getPrestaziones_R().remove(prestaziones_R);
        prestaziones_R.setPersonaID_R(null);
    }

    public List<Prestazione> getPrestaziones_F() {
        if (prestaziones_F == null) {
            prestaziones_F = new ArrayList<>();
        }
        return this.prestaziones_F;
    }

    public void setPrestaziones_F(List<Prestazione> prestaziones_F) {
        this.prestaziones_F = prestaziones_F;
    }

    public void addPrestaziones_F(Prestazione prestaziones_F) {
        getPrestaziones_F().add(prestaziones_F);
        prestaziones_F.setPersonaID_F(this);
    }

    public void removePrestaziones_F(Prestazione prestaziones_F) {
        getPrestaziones_F().remove(prestaziones_F);
        prestaziones_F.setPersonaID_F(null);
    }

}