/**
 * This file was generated by the JPA Modeler
 */
package entity;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * @author Marco
 */
@Entity
public class Prestazione {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String Data;

    @Basic
    private String Ora;

    @Basic
    private String attribute;

    @ManyToOne(targetEntity = Persona.class)
    private Persona persona;

    @ManyToOne(targetEntity = Persona.class)
    private Persona persona1;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getData() {
        return this.Data;
    }

    public void setData(String Data) {
        this.Data = Data;
    }

    public String getOra() {
        return this.Ora;
    }

    public void setOra(String Ora) {
        this.Ora = Ora;
    }

    public String getAttribute() {
        return this.attribute;
    }

    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }

    public Persona getPersona() {
        return this.persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    public Persona getPersona1() {
        return this.persona1;
    }

    public void setPersona1(Persona persona1) {
        this.persona1 = persona1;
    }

}