/**
 * This file was generated by the JPA Modeler
 */
package entity;

import java.util.Optional;
import javax.persistence.Basic;
import javax.persistence.Cacheable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

@Entity
@Cacheable(false)
public class Prestazione {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Basic
    private String data;

    @Basic
    private String ora;

    /**
     * Ricevente prestazione
     */
    @ManyToOne(targetEntity = Persona.class)
    private Persona personaID_R;

    /**
     * Fornitore della prestazione
     */
    @ManyToOne(targetEntity = Persona.class)
    private Persona personaID_F;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getData() {
        return this.data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public String getOra() {
        return this.ora;
    }

    public void setOra(String ora) {
        this.ora = ora;
    }

    public Optional<Persona> getPersonaID_R() {
        return Optional.ofNullable(this.personaID_R);
    }

    public void setPersonaID_R(Persona personaID_R) {
        this.personaID_R = personaID_R;
    }

    public Persona getPersonaID_F() {
        return this.personaID_F;
    }

    public void setPersonaID_F(Persona personaID_F) {
        this.personaID_F = personaID_F;
    }

}